name: Bug report
description: Report a bug you found when using AO.space
labels: ["Bug"]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        Please answer these questions before submitting your issue. Thanks!
  - type: textarea
    id: what_happened
    attributes:
      label: What happened
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: What you expected to happen
    validations:
      required: true
  - type: textarea
    id: how_to_reproduce
    attributes:
      label: How to reproduce it
    validations:
      required: true
  - type: input
    id: select_version
    attributes:
      label: Please select the version you are using （trial version or open-source version）
    validations:
      required: true
  - type: input
    id: server_version
    attributes:
      label: Server version
  - type: input
    id: client_version
    attributes:
      label: Client version
  - type: input
    id: browser
    attributes:
      label: Browser type & version, if used
  - type: textarea
    id: others
    attributes:
      label: Relevant error screenshots or links
