#!/bin/bash

# ============================================
# AO.Space Platform - Secure Setup Script
# ============================================
# This script helps you set up the platform securely:
# - Generates strong random passwords
# - Sets correct file permissions
# - Validates SSL certificates
# - Creates secure .env file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Generate secure random password
generate_password() {
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 24
}

echo ""
echo "============================================"
echo "  AO.Space Platform - Secure Setup"
echo "============================================"
echo ""

cd "$DEPLOY_DIR"

# Step 1: Check prerequisites
log_info "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    log_error "Docker is not installed. Please install Docker first."
    exit 1
fi

if ! command -v openssl &> /dev/null; then
    log_error "OpenSSL is not installed. Please install OpenSSL first."
    exit 1
fi

log_success "Prerequisites satisfied"

# Step 2: Get domain from user
echo ""
read -p "Enter your domain (e.g., example.com): " USER_DOMAIN

if [ -z "$USER_DOMAIN" ]; then
    log_error "Domain is required"
    exit 1
fi

# Step 3: Generate secure passwords
log_info "Generating secure passwords..."

MYSQL_ROOT_PASSWORD=$(generate_password)
MYSQL_PASSWORD=$(generate_password)
REDIS_PASSWORD=$(generate_password)

log_success "Passwords generated"

# Step 4: Create .env file
log_info "Creating secure .env file..."

cat > .env << EOF
# ============================================
# AO.Space Platform Configuration
# Generated by secure-setup.sh at $(date -Iseconds)
# ============================================
# WARNING: Keep this file secure and never commit to version control

# Domain
USER_DOMAIN=${USER_DOMAIN}

# Data Directory
DATA_DIR=./data

# MySQL
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=aoplatform
MYSQL_USER=aoplatform
MYSQL_PASSWORD=${MYSQL_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# Ports
NGINX_BIND_HTTP=80
NGINX_BIND_HTTPS=443
GT_BIND_PORT=61012

# Security
RATE_LIMIT_RPS=10
ENABLE_HSTS=true
CORS_ORIGINS=
EOF

chmod 600 .env
log_success ".env file created with secure permissions (600)"

# Step 5: Create data directories
log_info "Creating data directories..."

mkdir -p data/mysql data/redis data/ssl data/services

chmod 700 data/mysql
chmod 700 data/redis
chmod 700 data/ssl
chmod 755 data/services

log_success "Data directories created with secure permissions"

# Step 6: Check SSL certificate
echo ""
if [ -f "data/ssl/tls.crt" ] && [ -f "data/ssl/tls.key" ]; then
    log_success "SSL certificates found"

    # Validate certificate
    if openssl x509 -in data/ssl/tls.crt -noout -checkend 0 2>/dev/null; then
        CERT_EXPIRY=$(openssl x509 -in data/ssl/tls.crt -noout -enddate | cut -d= -f2)
        log_info "Certificate valid until: $CERT_EXPIRY"

        # Check if certificate matches domain
        CERT_CN=$(openssl x509 -in data/ssl/tls.crt -noout -subject | grep -o 'CN = [^,]*' | cut -d= -f2 | tr -d ' ')
        log_info "Certificate CN: $CERT_CN"
    else
        log_warn "Certificate may be expired!"
    fi

    chmod 600 data/ssl/tls.crt
    chmod 600 data/ssl/tls.key
else
    log_warn "SSL certificates not found in data/ssl/"
    echo ""
    echo "Please add your SSL certificate:"
    echo "  - data/ssl/tls.crt (certificate)"
    echo "  - data/ssl/tls.key (private key)"
    echo ""
    echo "You can get a certificate from:"
    echo "  1. Cloudflare Origin Certificate (free, 15 years)"
    echo "  2. Let's Encrypt (free, 90 days, auto-renew)"
    echo "  3. Your SSL provider"
fi

# Step 7: Display summary
echo ""
echo "============================================"
echo "  Setup Complete"
echo "============================================"
echo ""
echo "Domain: ${USER_DOMAIN}"
echo ""
echo "Credentials saved in .env file:"
echo "  - MySQL Root Password: ${MYSQL_ROOT_PASSWORD:0:4}****"
echo "  - MySQL User Password: ${MYSQL_PASSWORD:0:4}****"
echo "  - Redis Password: ${REDIS_PASSWORD:0:4}****"
echo ""
echo "IMPORTANT: Save these credentials securely!"
echo ""
echo "Next steps:"
echo "  1. Add SSL certificate to data/ssl/"
echo "  2. Configure DNS records (A and wildcard)"
echo "  3. Run: docker compose -f docker-compose.simple.yml up -d"
echo "  4. Run: ./scripts/init-network.sh"
echo ""
echo "Security reminders:"
echo "  - Configure firewall (ports: 80, 443, 61012/tcp, 3478/udp)"
echo "  - Enable automatic security updates"
echo "  - Set up log monitoring"
echo ""
